site_name: '小荔枝的百科'
site_url: 'https://szu.wiki/'

repo_name: 'libopenszu/wiki'
repo_url: 'https://github.com/libopenszu/wiki'

copyright: '除非另有声明，本网站内容采用知识共享署名-非商业性使用-相同方式共享授权。'

nav:
  - 校区:
    - 粤海校区:
      - 基本信息: university/yuehai/index/index.md
#    - 建筑:
#      - 宿舍:
#
    - 沧海校区:
      - 基本信息: university/canghai/index/index.md
    - 丽湖校区:
      - 基本信息: university/lihu/index/index.md
    - 罗湖校区:
      - 基本信息: university/luohu/index/index.md
    - 校区及建筑道路等命名变更: university/buildings_and_roads_renaming/index.md
  - 通用:
    - 微信公众号: universal/wechat_official_account/index.md
    - 校历:
      - 2020-2021学年第一学期: universal/calendar/2020-2021-1/index.md
    - 校务信箱: universal/mailbox/index.md
    - 校园卡:
      - 主要功能: universal/school_card/index.md
      - 充值方式: universal/school_card/index.md
      - 校园卡中心: universal/school_card/index.md
    - 校园码: universal/school_qrcode/index.md
    - 校园网络:
      - 教学区: universal/network/teaching_area/index.md
      - 宿舍区: universal/network/dormitory_area/index.md
      - 校外访问: universal/network/vpn/index.md
    - 校园邮箱:
      - 教师电子邮箱: universal/email/teacher/index.md
      - 学生电子邮箱: universal/email/student/index.md
    - 校长午餐会: universal/luncheon/index.md
    - 运动会:
      - 彩色跑: universal/sports_meeting/color_run/index.md
  - 学习:
    - 绩点: learning/gpa/index.md
    - 奖学金: learning/scholarship/index.md
    - 学习场所: 
      - 图书馆: learning/rooms_for_individual_study/library/index.md
      - 自习室: learning/rooms_for_individual_study/index.md
    - 培养方案:
      - 2020级:
        - 计算机科学与技术: learning/plans/2020/computer_science_and_technology/index.md
    - 选课: learning/course_selecting/index.md
    - 转专业: learning/change_major/index.md
    - 考研: learning/index.md
  - 生活:
    - 社团:
      - 首页: living/associations/index/index.md
      - 简阅艺文创新部落: living/associations/1001/index.md
      - 深圳大学荔进社: living/associations/2001/index.md
      - 深圳大学信息网络安全协会: living/associations/3001/index.md
      - 深圳大学招生志愿者协会: living/associations/4001/index.md
      - 深圳大学财经学会: living/associations/10001/index.md
      - 大学生健康协会: living/associations/10003/index.md
      - 深圳大学书法协会: living/associations/10004/index.md
      - 戏剧社（校戏）: living/associations/10005/index.md
      - 绿色风环保协会: living/associations/10006/index.md
      - 粤语协会: living/associations/10008/index.md
      - 韩语协会: living/associations/10009/index.md
      - 摄影协会: living/associations/10014/index.md
      - 深圳大学法学研究会: living/associations/10017/index.md
      - 深大手工创艺协会: living/associations/10018/index.md
      - 深圳大学吉他社: living/associations/10021/index.md
      - 思行社: living/associations/10022/index.md
      - 启言口才协会: living/associations/10023/index.md
      - 推理研究协会: living/associations/10024/index.md
      - 管理学会: living/associations/10025/index.md
      - 深圳大学魔术社: living/associations/10026/index.md
      - 深圳大学手语协会: living/associations/10027/index.md
      - 深圳大学天文协会: living/associations/10028/index.md
      - 深圳大学英语协会: living/associations/10030/index.md
      - 深圳大学模型社: living/associations/10031/index.md
      - 一白主持队: living/associations/11001/index.md
      - 深圳大学RobotPilots机器人俱乐部: living/associations/15001/index.md
      - 深圳大学拉丁打击乐社: living/associations/16002/index.md
      - AI俱乐部: living/associations/18001/index.md
      - 腾讯创新俱乐部: living/associations/18002/index.md
      - 深圳大学师范学院义务助学者联合会: living/associations/19003/index.md
      - 深圳大学茶艺社: living/associations/20003/index.md
      - 民商法协会: living/associations/20005/index.md
      - 壹个音乐社: living/associations/21001/index.md
      - 医学部辩论社: living/associations/21002/index.md
      - 医学部排球社: living/associations/21004/index.md
      - 医学部乒乓球社: living/associations/21005/index.md
      - 医学部足球社: living/associations/21007/index.md
      - 创意策划与设计管理协会: living/associations/22001/index.md
      - 深圳大学服装协会: living/associations/22003/index.md
      - 视觉传达协会: living/associations/22006/index.md
      - 微视觉造型协会: living/associations/22007/index.md
      - 深圳大学子归汉服社: living/associations/22009/index.md
      - 管理学院辩论队: living/associations/23001/index.md
      - 市场营销学会: living/associations/23002/index.md
      - 管理学院ERP俱乐部: living/associations/23003/index.md
      - 深圳大学人力资源学会: living/associations/23005/index.md
      - 深圳大学管理学院校聘社: living/associations/23006/index.md
      - 深圳大学青年纵横杂志社: living/associations/24004/index.md
      - 深圳大学历史研习社: living/associations/24005/index.md
      - 深圳大学电子与信息工程学院电子协会: living/associations/26002/index.md
      - 深圳大学定向越野俱乐部: living/associations/27001/index.md
      - 深圳大学毽球俱乐部: living/associations/27003/index.md
      - 深圳大学炫影轮滑协会: living/associations/27004/index.md
      - 深圳大学跆拳道俱乐部: living/associations/27005/index.md
      - 深圳大学国标舞协会丽湖分会: living/associations/27009/index.md
      - 深圳大学桥牌协会: living/associations/27010/index.md
      - 深圳大学瑜伽俱乐部: living/associations/27011/index.md
      - 深圳大学羽毛球协会: living/associations/27012/index.md
      - 深圳大学击剑协会: living/associations/27015/index.md
      - 深圳大学国标舞协会: living/associations/27016/index.md
      - 深圳大学桌球协会: living/associations/27018/index.md
      - 深圳大学围棋协会: living/associations/27019/index.md
      - 深圳大学排球协会: living/associations/27020/index.md
      - 深圳大学极限飞盘协会: living/associations/27021/index.md
      - 网球俱乐部: living/associations/27023/index.md
      - 深圳大学乒乓球协会: living/associations/27024/index.md
      - 深大ZEAL滑板社: living/associations/27025/index.md
      - 深大武术联合协会: living/associations/27027/index.md
      - 深圳大学电子竞技运动协会: living/associations/27028/index.md
      - 深圳大学魔方协会: living/associations/mofangxiehui/index.md
    - 水电费: living/utility_bill/index.md
    - 体育场馆:
      - 健身房: living/gym/index.md
    - 团学组织:
      - 首页: living/tuanxue/index/index.md
    - 校友会/同乡会:
      - 福建省: living/alumni_associations/fujian/index.md
      - 广东省:
        - 揭阳市: living/alumni_associations/guangdong/jieyang/index.md
        - 汕头市: living/alumni_associations/guangdong/shantou/index.md
      - 江西省: living/alumni_associations/jiangxi/index.md
  - 新生特供:
    - 首页: for_freshman/index/index.md
    - 深大盒子:
      - 简介: for_freshman/box/index/index.md
      - 2019年: for_freshman/box/2019/index.md
      - 2018年: for_freshman/box/2018/index.md
      - 2017年: for_freshman/box/2017/index.md
    - 必备物品: for_freshman/essential_items/index.md
    - 快递收寄: for_freshman/express_delivery/index.md
    - 深圳通: for_freshman/shenzhentong/index.md
    - 防盗窃和反欺诈: for_freshman/anti-theft-fraud/index.md
  - 关于:
    - 首页: index.md
    - 如何贡献: edit/index.md
  - 紧急情况:
    - 生命救援或紧急情况: emergency/index/index.md
    - 自动体外心脏除颤器（AED）分布: emergency/aed/index.md
    - 心理咨询: emergency/psychological_counseling/index.md

theme:
  features:
    - tabs
#    - instant
  language: 'zh'
  name: 'material'

extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/libopenszu'
    - icon: 'fontawesome/brands/telegram'
      link: 'https://t.me/szu_group'

extra_css:
  - css/extra.css

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.bootcdn.net/ajax/libs/mathjax/3.0.5/es5/tex-mml-chtml.js

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.mark
  - pymdownx.tilde
